name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java runtime 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          branch: "main"
          heroku_api_key: "95725347-4959-4454-ae92-37abf2b437ef"
          heroku_app_name: "ec-api"
          heroku_email: "lulueve3@gmail.com"
          args: --skip-database-initialization

