name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to Heroku
        run: |
          heroku login -i
          heroku config:set SPRING_DATASOURCE_INITIALIZATION_MODE=never --app ec-api
          heroku plugins:install java
          heroku deploy:jar target/*.jar --app ec-api --jdk 17
        env:
          HEROKU_API_KEY: "95725347-4959-4454-ae92-37abf2b437ef"